# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/25dfaf44-3095-46e9-ab9a-855b22d62ffa";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-34577c87-a69f-43c7-8632-116dd3bbff2e".device =
    "/dev/disk/by-uuid/34577c87-a69f-43c7-8632-116dd3bbff2e";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1FC6-CA27";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/6e4a6637-36f4-498a-90b6-6cefdf005a05";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-506d3594-254e-4bd4-bcff-63bd086f7621".device =
    "/dev/disk/by-uuid/506d3594-254e-4bd4-bcff-63bd086f7621";

  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-uuid/e3851b32-ce09-4eff-aca6-90695244c496";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-8d5345f1-e0d3-43a2-ba27-b3c20c92d03d".device =
    "/dev/disk/by-uuid/8d5345f1-e0d3-43a2-ba27-b3c20c92d03d";

  swapDevices = [{
    device = "/swapfile";
    size = 16 * 1024; # 16GB
  }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp11s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
